#!/bin/bash

function error () {
	1>&2 echo -e "$@"
	exit 1
}

function notification () {
	notify-send "$@"
}

function shout () {
	notification "$@"
	error "$@"
}

function send () {
	METHOD=$1
	URL=$2
	[ ! -z "$3" ] && DATA="{$3}" || DATA=""
	BEARERHEADERS="Authorization: Bearer ${TOKEN}"
	DATAHEADERS='Content-Type: application/json; charset=utf-8'
	
	curl -sX "$METHOD" -k \
		-H "Authorization: Bearer ${TOKEN}" \
		-H "Content-Type: application/json; charset=utf-8" \
		--connect-timeout 2 \
		--max-time 5 \
		--data "$DATA" "$URL"
}

CONFIGFILE="$HOME/.config/birthdayserver"
TOKENFILE="$HOME/.config/birthdaytoken"

[ ! -f $CONFIGFILE ] && shout "SPECIFY BIRTHDAY SERVER ADDRESS\n$CONFIGFILE"
[ ! -f $TOKENFILE ] && shout "AUTHORIZATION TOKEN REQUIRED\n$TOKENFILE"

URL="$(cat $CONFIGFILE)"
TOKEN="$(cat $TOKENFILE)"

[ "$(isonline $URL)" = "offline" ] && shout "Birthday server unreachable!" 

# bdcli today
[ "$1" = "today" ] && send GET "$URL/birthdays/today" | jq --raw-output 'map(.person) | .[]' && exit 0

# bdcli 26 5
[ $# -eq 2 ] && send GET "$URL/birthdays/date/$2/$1" | jq --raw-output 'map(.person) | .[]' && exit 0

# bdcli insert
if [ "$1" = "insert" ]; then
	echo "Insert a birthday"
	read -p 'Name: ' name
	read -p 'Day: ' day
	read -p 'Month: ' month
	DATA=\"Day\":\"$day\",\"Month\":\"$month\",\"Person\":\"$name\"

	send POST "$URL/birthdays/insert" "$DATA" | jq --raw-output
	exit 0
fi

# bdcli 5
if [[ $1 =~ ^(0?[1-9]|1[012])$ ]]; then
	send GET "$URL/birthdays/month/$1" | jq --raw-output 'map(.person) | .[]'
	exit 0
fi

# bdcli delete
if [ "$1" = "delete" ]; then
	echo "Delete a birthday"
	read -p 'Name: ' name
	
	send DELETE "$URL/birthdays/delete/$name" | jq --raw-output 
	exit 0
fi

# bdcli person
if [ "$1" = "person" ]; then
	echo "Find someone's birthday"
	read -p 'Name: ' name
	echo $name

	send GET "$URL/birthdays/$name" | jq --raw-output '.day,.month' 2>/dev/null | tr "\n" " " && echo 
	exit 0
fi
