#!/bin/sh
[ $(id -u) -ne 0 ] && errormessage "Run as root" && exit 1

pacman -S easy-rsa openvpn

cd /etc/easy-rsa
export EASYRSA=$(pwd)

cp $SCRIPTDIR/configs/easy-rsa/vars /etc/easy-rsa/vars

export EASYRSA_VARS_FILE=/etc/easy-rsa/vars
easyrsa init-pki
easyrsa build-ca
