#!/bin/sh

MODENAME="2560x1440_40.00"
OUT="HDMI2"

if [ $(xrandr | grep $MODENAME | wc -l) -eq 0 ]; then
	xrandr --newmode "$MODENAME"  201.00  2560 2720 2984 3408  1440 1443 1448 1476 +hsync +vsync
	xrandr --addmode $OUT "$MODENAME"
fi

xrandr --output LVDS1 --off --output $OUT --mode "$MODENAME" 
