#!/bin/sh
[ $(id -u) -ne 0 ] && errormessage "Run as root" && exit 1

pacman -S openvpn

CLIENTDIR=/tmp/$(ls /tmp/ | grep ovpnclient | fzf)

# copy certificate into signed directory
[ ! -d /etc/easy-rsa/pki/signed ] && mkdir -p /etc/easy-rsa/pki/signed
cp $CLIENTDIR/*.crt /etc/easy-rsa/pki/signed

read -p "Please provide the name of the vpn server: " server

read -p "This is going tor reset folder /etc/openvpn/client/$server/. Proceed? (y/n) " reset
[ ! "$reset" = "y" ] && exit 1

mkdir -p /etc/openvpn/client/$server
cp $CLIENTDIR/* /etc/openvpn/client/$server/

chmod 0400 /etc/openvpn/client/$server/*
chown root:root /etc/openvpn/client/$server/*

echo "Finished copying certificates from $CLIENTDIR"
