#!/bin/sh

# intellij wm fix
wmname LG3D

# daemons
xset b off
flameshot &
numlockx &
dunst &

sxhkd -c $HOME/.config/sxhkd/sxhkdrc_$PROFILE &

amixer set Capture nocap 

if [ ! $PROFILE = "ws" ]; then
	amixer set Master mute 
fi

# wm and visual changes
if [ $WM = "dwm" ]; then
	setbg &
	dbc &
	firefox & # https://ucilnica.fri.uni-lj.si/login/index.php &
	discord &
fi

calendar & 
st &
birthdays & 
